### ISSUE TITLE
iPhone5,2 wifi toggle grayed out after downgrading to iOS 8.4.1

### ISSUE THREAD

**Issue by CodeyMoore** [LukeZGD/iOS-OTA-Downgrader#78] opened 2021-01-22 14:52 UTC
After downgrading my iPhone5,2 I can't use wifi at all.
Any help would be greatly appreciated!

Cheers

**Comment by LukeZGD** [comment] 2021-01-23 11:13
Not sure if this is caused by downgrading.. Does it work fine when restored back to the latest version (10.3.4)? Also when downgrading, is the jailbreak option turned on or off?

**Comment by CodeyMoore** [comment] 2021-01-23 11:57
Currently restoring to iOS 10.3.4 to check if wifi works (it was working before I downgraded).
The jailbreak option was on when I downgraded.

**Comment by LukeZGD** [comment] 2021-01-23 14:40
> Going to try and downgrade without the jailbreak option enabled.
> Will I still be able to jailbreak later if I dont enable it?

Yes you may downgrade with the jailbreak option turned off and still jailbreak later by sideloading EtasonJB, let me know if Wi-Fi works with the jailbreak option turned off (I think this is a side-effect of baseband problems)

**Comment by CodeyMoore** [comment] 2021-01-23 14:43
> > Going to try and downgrade without the jailbreak option enabled.
> > Will I still be able to jailbreak later if I dont enable it?
> 
> Yes you may downgrade with the jailbreak option turned off and still jailbreak later by sideloading EtasonJB, let me know if Wi-Fi works with the jailbreak option turned off (I think this is because of baseband problems when jailbreak option is on, I may try to find a solution sometime)

I'm attempting that now but im getting this error with my ssh host file even though the file is empty

"sh: scp: command not found
lost connection

[Error] Cannot connect to device via SSH. Please check your ~/.ssh/known_hosts file and try again 
* You may also run: rm ~/.ssh/known_hosts"

**Comment by LukeZGD** [comment] 2021-01-23 14:53
> scp: command not found

Not sure what's going on there, you may want to try re-installing dependencies (instructions are in the readme)

**Comment by CodeyMoore** [comment] 2021-01-23 15:02
> scp

I have but it made no difference.
I can manually ssh into my iPhone 5 but the downgrader cant for some reason

**Comment by LukeZGD** [comment] 2021-01-23 15:04
> > scp
> 
> I have but it made no difference.
> I can manually ssh into my iPhone 5 but the downgrader cant for some reason

What macOS version/Linux distro are you using?
It's really weird to have a `command not found` for `scp` if dependencies are installed

**Comment by CodeyMoore** [comment] 2021-01-23 15:06
> > > scp
> > 
> > 
> > I have but it made no difference.
> > I can manually ssh into my iPhone 5 but the downgrader cant for some reason
> 
> What macOS version/Linux distro are you using?
> It's really weird to have a `command not found` for `scp` if dependencies are installed

macOS Catalina 10.15.7 (19H114).

Work this out though. If I run "scp" that works

**Comment by LukeZGD** [comment] 2021-01-23 15:07
> > > > scp
> > > 
> > > 
> > > I have but it made no difference.
> > > I can manually ssh into my iPhone 5 but the downgrader cant for some reason
> > 
> > 
> > What macOS version/Linux distro are you using?
> > It's really weird to have a `command not found` for `scp` if dependencies are installed
> 
> macOS Catalina 10.15.7 (19H114).
> 
> Work this out though. If I run "scp" that works

Ah sorry I can't help out with macOS stuff, I don't have means to test with Macs anymore

**Comment by CodeyMoore** [comment] 2021-01-23 15:09
> > macOS Catalina 10.15.7 (19H114).
> > Work this out though. If I run "scp" that works
> 
> Ah sorry I can't help out with macOS stuff, I don't have means to test with Macs anymore

ohh okay all good. I've redownloaded the whole repo and retrying

**Comment by CodeyMoore** [comment] 2021-01-23 15:56
I managed to get it to all work by installing openssh and rebooting (not sure what helped more).
The WiFi is still greyed out and the WiFi address is "n/a".

**Comment by LukeZGD** [comment] 2021-01-23 16:13
> the WiFi address is "n/a"

Ah I think I know what's going on now, I'll test things out on my iPhone5,2 later

**Comment by LukeZGD** [comment] 2021-01-24 03:51
I think this should be fixed by 6f0fdbf, which removes the unnecessary nvram wifiaddr "workaround"

Restore back to 10.3.4, jailbreak and install MTerminal, run:

```
su
(enter password, default is alpine)
nvram -d wifiaddr
```

Then proceed downgrading with iOS-OTA-Downgrader (either of the jailbreak option should work fine now)

**Comment by CodeyMoore** [comment] 2021-01-26 04:43
> I think this should be fixed by [6f0fdbf](https://github.com/LukeZGD/iOS-OTA-Downgrader/commit/6f0fdbf691c825c7e300240edea68c3fc10aeb92), which removes the unnecessary nvram wifiaddr "workaround"
> 
> Restore back to 10.3.4, jailbreak and install MTerminal, run:
> 
> ```
> su
> (enter password, default is alpine)
> nvram -d wifiaddr
> ```
> 
> Then proceed downgrading with iOS-OTA-Downgrader (either of the jailbreak option should work fine now)


I've since tried this version but now I can't because I get stuck at this point

![Screen Shot 2021-01-26 at 3 13 27 pm](https://user-images.githubusercontent.com/21144094/105801449-0de40c80-5fe9-11eb-8bfa-c4dedb0eb90d.png)

**Comment by LukeZGD** [comment] 2021-01-26 14:29
This happens to me sometimes as well (getting stuck at the SSH part)

What worked for me is re-install both OpenSSH and Dropbear, reboot the device, rejailbreak then try again

**Comment by CodeyMoore** [comment] 2021-01-27 00:12
Thank you, it's working now.

**Closed** 2021-01-27 01:58 UTC

**Comment by nousernameforu** [comment] 2025-06-10 22:09
> I think this should be fixed by [6f0fdbf](https://github.com/LukeZGD/Legacy-iOS-Kit/commit/6f0fdbf691c825c7e300240edea68c3fc10aeb92), which removes the unnecessary nvram wifiaddr "workaround"
> 
> Restore back to 10.3.3/10.3.4, jailbreak and install MTerminal, run:
> 
> ```
> su
> (enter password, default is alpine)
> nvram -d wifiaddr
> ```
> 
> Then proceed downgrading with iOS-OTA-Downgrader (either of the jailbreak option should work fine now)

Still relevant. Wifi was broken when downgraded, "nvram -d wifiaddr" fixed it.
