### ISSUE TITLE
[Continuation] iOS 8.4.1: Cydia icon not displaying on home screen

### ISSUE THREAD

**Issue by mariobrostech** [LukeZGD/iOS-OTA-Downgrader#65] opened 2020-10-24 20:26 UTC
Hello again,

Is there any way that the fix you found to show the Cydia icon on the home screen can be integrated directly into the script (preferred), or can the tweak that fixes it be automatically installed? I’m currently beta testing a tweak that is highly unstable and requires me to restore my device often, so this would be a nice timesaver for me :)

Thanks again!

**Comment by mariobrostech** [comment] 2020-10-24 20:28
Also, I’m more than happy to test any changes you make on my testing device so you don’t have to; just make another branch (or push it to the main one if you’re ok with potential issues), and let me know if you come up with anything.

**Comment by LukeZGD** [comment] 2020-10-25 02:16
Not sure tbh, I can't include the debs in the custom IPSW because AutoInstall is broken with LaunchDaemons not loading in startup, requiring to add my repo and installing the fixes from there

**Comment by C-r-e-a-l** [comment] 2020-10-26 23:40
> Hello again,
> 
> Is there any way that the fix you found to show the Cydia icon on the home screen can be integrated directly into the script (preferred), or can the tweak that fixes it be automatically installed? I’m currently beta testing a tweak that is highly unstable and requires me to restore my device often, so this would be a nice timesaver for me :)
> 
> Thanks again!

same issue here

**Comment by UInt2048** [comment] 2020-11-16 00:55
For reference, the fix that was found is at #63

**Comment by mariobrostech** [comment] 2020-12-20 17:35
> Not sure tbh, I can't include the debs in the custom IPSW because AutoInstall is broken with LaunchDaemons not loading in startup, requiring to add my repo and installing the fixes from there first

Sorry for the late reply, but this just came into my mind: would there be some way to bundle etasonJB? That hasn't had any issues relating to the Cydia icon not showing up on the Springboard, at least in my experience. Or, does it maybe have to do with stashing being enabled by default with your tool?

Thanks, and sorry for being a pain :)

**Comment by LukeZGD** [comment] 2020-12-22 09:48
> bundle etasonJB?

The etasonJB untether and Cydia are already bundled in with the jailbreak option. If you mean the etasonJB app, not sure if I can do that

**Comment by LukeZGD** [comment] 2021-03-12 08:25
Attempts to pre-install the debs of the fixes are in the `fixes` branch, but it still doesn't seem to work.. 

Anyways I'll try a bit more next week then if I really can't find a way then I might probably just close as wontfix, as the issue isn't that urgent because the fixes are available in my repo

**Closed** 2021-03-22 07:29 UTC

**Comment by LukeZGD** [comment] 2021-09-06 09:01
This is now fixed by #129 without needing the icon fix tweak
