### ISSUE TITLE
iPhone 4s APTicket can't be used for restoring this device

### ISSUE THREAD

**Issue by rafli980** [LukeZGD/iOS-OTA-Downgrader#197] opened 2022-07-22 07:18 UTC
Terminal Output : 
******* iOS-OTA-Downgrader ******* 
 ```
- Downgrader script by LukeZGD -  

[Log] Detected libimobiledevice and libirecovery installed from Homebrew (Intel Mac) 
[Log] Running on platform: macos (10.14.6) 
[Log] Checking Internet connection... 
[Log] Finding device in Normal mode... 
[Log] Finding device in DFU/recovery mode... 
[Log] iPhone4,1 connected in DFU mode. 
[Log] ECID: 6882812388869 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      4) (Re-)Install Dependencies
2) Save OTA Blobs	      5) (Any other key to exit)
3) Create Custom IPSW
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) Other (use SHSH blobs)
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2

* DFU Advanced Menu 
* This menu is for ADVANCED USERS ONLY. 
* If you do not know what you are doing, EXIT NOW by pressing Ctrl+C and restart your device in normal mode. 
[Input] Select the mode that your device is currently in: 
1) kDFU mode
2) pwnDFU mode (A5)
3) Any other key to exit
#? 2
* Make sure that your device is in pwnDFU mode using an Arduino+USB Host Shield! 
* This option will not work if your device is not in pwnDFU mode. 
[Input] Press Enter/Return to continue (or press Ctrl+C to cancel) 
[Input] No iBSS Option 
* If you already have sent pwned iBSS manually, select Y. If not, select N. 
* This option is disabled by default (N). 
[Input] Enable this option? (y/N): 

[Input] Send iBSS Option 
* To send pwned iBSS using ipwndfu, select Y. (does not work on ARM Macs) 
* To let futurerestore send iBSS, select N. (likely does not work) 
* For macOS 12 and newer, install python2 first before selecting ipwndfu. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): y
[Log] Patching iBSS... 
[Log] Sending iBSS... 
done!
[Log] Downgrading iPhone4,1 in kDFU/pwnDFU mode... 
[Log] Select your options when asked. If unsure, go for the defaults (press Enter/Return). 


[Input] Jailbreak Option 
* When this option is enabled, your device will be jailbroken on restore. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): y
[Log] Using p0sixspwn for the jailbreak 
[Log] Jailbreak option enabled. 

[Input] Memory Option for creating custom IPSW 
* This option makes creating the custom IPSW faster, but it requires at least 8GB of RAM. 
* If you do not have enough RAM, disable this option and make sure that you have enough storage space. 
* This option is enabled by default (Y). 
[Input] Enable this option? (Y/n): y
[Log] Memory option enabled. 

[Log] Found existing saved 6.1.3 blobs: saved/shsh/6882812388869_iPhone4,1_n94ap_6.1.3-10B329_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2 
[Log] Found existing Custom IPSW. Skipping 6.1.3 IPSW verification. 
[Log] Device is already in DFU mode 
[Log] Found existing Custom IPSW. Skipping IPSW creation. 
[Log] Setting restore IPSW to: iPhone4,1_6.1.3_10B329_Custom.ipsw 
[Log] Extracting IPSW: iPhone4,1_6.1.3_10B329_Custom.ipsw 
[Log] Proceeding to futurerestore... 
[Log] Running futurerestore with command: ./resources/tools/futurerestore_macos_x86_64 -t "saved/shsh/6882812388869_iPhone4,1_n94ap_6.1.3-10B329_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2" --use-pwndfu --no-ibss -b saved/baseband/Trek-6.7.00.Release.bbfw -p saved/iPhone4,1/BuildManifest.plist "iPhone4,1_6.1.3_10B329_Custom.ipsw" 
Version: v2.0.0-test(a58821b95f6417ad649ed7a5460337dcd82e200e-259)
img4tool version: 0.197+git20210129-aca6cf005c94caf135023263cbb5c61a0081804f-RELEASE
libipatcher version: 0.86+git20210810-6a3b358b673e74c2be9f9b8a74a63b80dd94abf1-RELEASE
Odysseus for 32-bit support: yes
Odysseus for 64-bit support: yes
[INFO] 32-bit device detected
futurerestore init done
reading signing ticket saved/shsh/6882812388869_iPhone4,1_n94ap_6.1.3-10B329_3a88b7c3802f2f0510abc432104a15ebd8bd7154.shsh2 is done
Did set SEP+baseband path and firmware
ERROR: Unable to connect to device?!
ERROR: Unable to get FirmwarePreflightInfo
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening saved/iPhone4,1/BuildManifest.plist
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Serving HTTP on 0.0.0.0 port 8888 ...
Sending TSS request attempt 1... response successfully received
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as n94ap, iPhone4,1
Extracting BuildManifest from iPSW
Product version: 6.1.3
Product build: 10B329 Major: 10
Device supports Image4: false
[TSSR] Checking BuildIdentity 0
[TSSR] Selected BuildIdentity for request
checking APTicket to be valid for this restore...
[Error] ECID inside APTicket does not match device ECID
APTicket is valid for    6882812388869 (dec) but device is    3564287966605 (dec)
Cleaning up...
[exception]:
what=APTicket can't be used for restoring this device

code=83886097
line=1280
file=futurerestore.cpp
commit count=259:
commit sha  =a58821b95f6417ad649ed7a5460337dcd82e200e:
Done: restoring failed!

[Log] Restoring done! Read the message below if any error has occurred: 
* Please read the "Troubleshooting" wiki page in GitHub before opening any issue! 
* Your problem may have already been addressed within the wiki page. 
* If opening an issue in GitHub, please provide a FULL log. Otherwise, your issue may be dismissed. 

```

**Comment by LukeZGD** [comment] 2022-07-22 07:52
There seems to be a problem with the script when converting the hex ECID to decimal, I will be checking on this later

For now, you can try uninstalling libirecovery from Homebrew, delete `first_run` file in `resources`, then try again. Not sure if this will help any though

**Comment by LukeZGD** [comment] 2022-07-22 09:04
Please try again with e8de405, hopefully it fixes ECID reading now

If that still did not work and ECID reading is still wrong, I have now also added a new argument `EntryDevice` to enter ProductType and ECID manually. To use, run `./restore.sh EntryDevice`

**Comment by rafli980** [comment] 2022-07-22 09:31
the ECID reading is still wrong. however, when i tried to use EntryDevice argument to enter the ECID manually, it didn't recognize the PwnedDevice argument so it just kicked me out. can i use 2 arguments in the same time? I couldn't get jailbreak working cause it's Setupapp deleted device (if you know what i mean). so, I didn't have any option except using an Arduino

```
[Raflis-MacBook-Pro:~] rafli$ /Users/rafli/Desktop/iOS-OTA-Downgrader-e8de405d935b7de69b910b1ceddd7dfd7b778e2f/restore.sh EntryDevice PwnedDevice

******* iOS-OTA-Downgrader ******* 
 - Downgrader script by LukeZGD -  

[Log] Detected libimobiledevice and libirecovery installed from Homebrew (Intel Mac) 
[Log] Running on platform: macos (10.14.6) 
[Log] Checking Internet connection... 
[Log] Finding device in Normal mode... 
[Log] Finding device in DFU/recovery mode... 
[Input] Enter ProductType (eg. iPad2,1): iPhone4,1
[Input] Enter UniqueChipID (ECID, must be decimal): 2344113529736
[Log] iPhone4,1 connected in DFU mode. 
[Log] ECID: 2344113529736 
*** Main Menu *** 
[Input] Select an option: 
1) Downgrade Device	      4) (Re-)Install Dependencies
2) Save OTA Blobs	      5) (Any other key to exit)
3) Create Custom IPSW
#? 1

[Input] Select iOS version: 
1) iOS 8.4.1		    3) Other (use SHSH blobs)
2) iOS 6.1.3		    4) (Any other key to exit)
#? 2

[Error] 32-bit A5 device detected in DFU mode. 
* Please put the device in normal mode and jailbroken before proceeding. 
* Exit DFU mode by holding the TOP and HOME buttons for 15 seconds. 
* For usage of the DFU Advanced Menu, add PwnedDevice as an argument. 
* For more details, read the "Troubleshooting" wiki page in GitHub 
```

**Comment by LukeZGD** [comment] 2022-07-22 09:44
Oops, sorry about that. Please try again with [c7c5427](https://github.com/LukeZGD/iOS-OTA-Downgrader/commit/c7c542729ec9c7ac13b374230d757ec3dba1de8b), it should be able to handle more than 1 arg now

**Comment by rafli980** [comment] 2022-07-22 11:29
![IMG_20220722_182343](https://user-images.githubusercontent.com/70388278/180429727-8811ada2-70d3-4d14-85ba-2cfab1fda00f.jpg)
it worked! unfortunately, the automatic ECID reader was still broken tho. but manually typing the ECID fix the problem. you can close this issue whenever you want, keep up the good work! 👍

**Comment by LukeZGD** [comment] 2022-07-22 11:49
Thanks for letting me know, it's unfortunate that the ECID reading didn't work for you, I tested in my devices and they all worked correctly so I don't really know the cause of it

In any case, the `EntryDevice` argument is now added for situations like this, and the script can now handle multiple arguments as well. Closing the issue now

**Closed by LukeZGD** 2022-07-22 11:49 UTC
