### ISSUE TITLE
iOS 8.4.1: Cydia crashes on startup (S5L8942)

### ISSUE THREAD

**Issue by cherry-412** [LukeZGD/iOS-OTA-Downgrader#70] opened 2020-11-23 03:46 UTC
**iPad2,5** and **iPad3,1** downgraded to 8.4.1 via **Arduino A5 / A5X checkm8** and **Jailbreak enabled** results in Cydia being installed to the device, but with Cydia instantly crashing at launch (launched via cydia:// in safari due to the Cydia icon not appearing).

As described in the readme:
> Warning: If your device bootloops with EtasonJB, it may not work with the jailbreak option as well! (I think this applies to some but not all 8942/8945 users) If this happens, bootloop protection will trigger and you won't be able to open Cydia

Adding to that, I've gotten EtasonJB on both of these devices before, namely the RC2 and RC5 versions in app format, installed via getzeus.app and faced no issues keeping them untethered. The issue occurs only if using iOS-OTA-Downgrader to install a jailbroken version of iOS 8.4.1.

Both of my devices are iCloud Locked, but Cydia and the script's ability to install the custom ipsw are unaffected by this. Only apple official cables were used and I ran the script on macOS 10.14 via hackintosh.

I attempted the following:
- Excluded  _etasonJB-untether.tar_ from the ipsw, which resulted in no change whatsoever
- Downgraded without the jailbreak enabled and manually copied the jailbreak files over via sftp (this was done by Arduino pwning the device and using Sliver 5.5 to access the user partition over usb), but either this method doesn't work or I didn't do it properly
- [Someone in a different issue](https://github.com/LukeZGD/iOS-OTA-Downgrader/issues/66#issuecomment-716909561) managed to jailbreak it via 3uTools, but the process aborts due to the devices lacking activation

Are there perhaps any other workarounds? Or is the reason behind bootloop protection firing up on these devices known? I can help test if needed.

**Comment by LukeZGD** [comment] 2020-11-23 04:00
It really only comes down to EtasonJB being the problem.. Unfortunately tihmstar didn't update the untether to fix this issue which leaves it broken on these devices. I experience the same issues in iPad3,3, and I don't really have any workaround for this, someone else needs to fix the untether or create an alternative

**Comment by albyvar25** [comment] 2020-12-17 06:57
Maybe you can try putting the log file which is checked by the etason untether binary to report that the untether never failed and make this file permanent with chattr uchg (or something like that)

**Comment by LukeZGD** [comment] 2020-12-22 09:48
> Maybe you can try putting the log file which is checked by the etason untether binary to report that the untether never failed and make this file permanent with chattr uchg (or something like that)

I tried that before actually, but it took over 30 mins to boot just once.. I don't think I want to put that in, but maybe I'll try again sometime

**Comment by albyvar25** [comment] 2021-01-04 11:50
> > Maybe you can try putting the log file which is checked by the etason untether binary to report that the untether never failed and make this file permanent with chattr uchg (or something like that)
> 
> I tried that before actually, but it took over 30 mins to boot just once.. I don't think I want to put that in, but maybe I'll try again sometime

Can you tell me what did you put inside the file?

**Comment by LukeZGD** [comment] 2021-03-12 03:15
Revisiting this issue, I have successfully disabled the "bootloop protection" of EtasonJB thru the power of hex editing! As tested with my iPad3,3, it will now be able to attempt booting for more than 10 times.. And from the tests, it can boot as fast as 3 minutes, or it may take over 20 minutes for a successful boot. I will be pushing it soon. It may not be a very good workaround, but it works, so...

**Comment by albyvar25** [comment] 2021-03-12 07:17
Awesome! Thanks a lot!

**Comment by LukeZGD** [comment] 2021-03-12 08:26
Workaround fixes are now pushed and included, and a tweak has been released in my repo for the patch as well for those that downgraded and jailbroken with other methods

**Comment by albyvar25** [comment] 2021-03-13 12:14
Hi, thanks for working on it! Anyway I tried using the master branch but Cydia is still crashing. My device is an iPod 5

**Comment by LukeZGD** [comment] 2021-03-13 12:30
> Hi, thanks for working on it! Anyway I tried using the master branch but Cydia is still crashing. My device is an iPod 5

Yeah about that.. I think that it is currently still not working on A5 8942 devices for some reason, I have no idea why that is

It has been [reported to me on Reddit](https://www.reddit.com/r/LegacyJailbreak/comments/m3bjw1/release_etasonjb_disable_bootloop_protection/gqokccz/) that it also crashes on iPad mini 1 (also an 8942 device)

I don't have an A5 8942 device, but I have test devices for the other ones (A5 8940, A5X, and A6), and they all work just fine

**Comment by LukeZGD** [comment] 2021-03-13 12:53
To those that can help me test, try testing things out with the jailbreak option disabled, and sideloading EtasonJB through other means (Xcode, signing service, etc.), then test if the jailbreak and untether works through reboots (without, and with the EtasonJB Disable Bootloop Protection from my repo)

**Comment by albyvar25** [comment] 2021-03-22 13:06
Maybe we could patch installd and boot with a patched kernel to allow free developer subscription signed apps to be installed on-device (would be useful for people who have bypassed devices)

**Comment by LukeZGD** [comment] 2021-03-23 15:32
> Maybe we could patch installd and boot with a patched kernel to allow free developer subscription signed apps to be installed on-device (would be useful for people who have bypassed devices)

Yeah that would be really nice, but I don't really know how to do that..

**Comment by LukeZGD** [comment] 2021-04-08 02:58
dora2ios has released an 8.4.1 untether: https://github.com/dora2-iOS/daibutsu

Currently it is incomplete, but this can be a potential alternative to the Etason untether if it does work well for all 32-bit devices

**Comment by LukeZGD** [comment] 2021-09-05 15:13
This issue should now be fixed by using daibutsuCFW instead of EtasonJB

See [my comment in issue #93](https://github.com/LukeZGD/iOS-OTA-Downgrader/issues/93#issuecomment-913170097) for more details

**Closed** 2021-09-06 08:50 UTC

**Comment by v-marinkov** [comment] 2021-10-01 23:09
@LukeZGD I just ran the downgrader twice on an iPhone 4s from 9.3.6 to 8.4.1. In both cases everything went smoothly but Cydia crashes when launched. My understanding is that daibutsu has been used (there is no EtasonJB icon) and yet Cydia crashes.
At the end of the downgrade it shows this message
`./resources/downgrade.sh: line 3: 602492 Segmentation fault      $idevicerestore -ewy $IPSWRestore.ipsw`

I tried settings and content resets with no change. Am I missing any final step after the downgrade?
Many thanks

**Comment by LukeZGD** [comment] 2021-10-02 01:11
> @LukeZGD I just ran the downgrader twice on an iPhone 4s from 9.3.6 to 8.4.1. In both cases everything went smoothly but Cydia crashes when launched. My understanding is that daibutsu has been used (there is no EtasonJB icon) and yet Cydia crashes. At the end of the downgrade it shows this message `./resources/downgrade.sh: line 3: 602492 Segmentation fault $idevicerestore -ewy $IPSWRestore.ipsw`
> 
> I tried settings and content resets with no change. Am I missing any final step after the downgrade? Many thanks

Please provide more info, I'm assuming this is on Linux?

**Comment by v-marinkov** [comment] 2021-10-02 09:06
Yes, PopOS 20.04. I let the tool do everything - download the IPSW and jailbreak it. It says it used daibutsu and successfully downgraded. There is the Cydia icon but it crashes when launched.
I tried jailbreaking with EtasonJB and Home Depot afterwards but the first one did nothing, while the latter said "unknown device iPhone 4,1 > provide custom offsets" and I don't have those.

I just talked to another user on Discord who had the exact same experience on an iPad 2 using both Linux and Windows.

I can provide you with the full terminal log if there is no sensitive information. Is there an automatically dumped log too?

**Comment by LukeZGD** [comment] 2021-10-02 12:40
> Yes, PopOS 20.04. I let the tool do everything - download the IPSW and jailbreak it. It says it used daibutsu and successfully downgraded. There is the Cydia icon but it crashes when launched. I tried jailbreaking with EtasonJB and Home Depot afterwards but the first one did nothing, while the latter said "unknown device iPhone 4,1 > provide custom offsets" and I don't have those.
> 
> I just talked to another user on Discord who had the exact same experience on an iPad 2 using both Linux and Windows.
> 
> I can provide you with the full terminal log if there is no sensitive information. Is there an automatically dumped log too?

No automatic logs, but you may save the terminal output and share via pastebin or similar. Just make sure to redact the serial number outputted by idevicerestore

I have also tested on my iPhone 4S just now and Cydia opens just fine, and daibutsu untether is installed successfully. Not sure what the problem is on your end

**Comment by v-marinkov** [comment] 2021-10-02 13:11
I ended up downgrading again without a jailbreak and then manually installing daibutsu. It works fine now. Thanks for the great tool but keep in mind that something may play up with daibutsu

**Comment by LukeZGD** [comment] 2021-10-02 13:30
> I ended up downgrading again without a jailbreak and then manually installing daibutsu. It works fine now. Thanks for the great tool but keep in mind that something may play up with daibutsu

Yeah unfortunately I won't really be able to fix an issue that I cannot replicate, am pretty sure same goes with #135
