### ISSUE TITLE
Cellular (mobile data to be exact) doesn't work after downgrade to 8.4.1 on iPhone5,2

### ISSUE THREAD

**Issue by beangoosedev** [LukeZGD/iOS-OTA-Downgrader#159] opened 2022-01-24 15:49 UTC
After downgrading my iPhone 5 to iOS 8.4.1, Mobile data doesn't work at all. Is this a baseband issue?

OS used to downgrade: macOS 10.13.6

**Comment by beangoosedev** [comment] 2022-01-24 18:56
It is on 11.80.00 currently and it did work on iOS 10

**Comment by LukeZGD** [comment] 2022-01-25 10:21
> It is on 11.80.00 currently 

Might be something with the carrier settings then, idk. Anyways, the issue is not related with the script, so I'm closing this

**Closed by LukeZGD** 2022-01-25 10:21 UTC
